### ISSUE TITLE
App4 does not compile

### ISSUE THREAD

**Issue by paolosalvatori** [karlospn/opentelemetry-tracing-demo#6]
After upgrading the OpenTelemetry packages to the latest version, it seems that the `TracerProviderBuilder` class does not contain any `Configure` method. Hence, the following call in the `App4` does not compile.

```csharp
.Configure((sp, builder) =>
{
    RedisCache cache = (RedisCache)sp.GetRequiredService<IDistributedCache>();
    builder.AddRedisInstrumentation(cache.GetConnection());
})
```

**Comment by karlospn** [comment]
> After upgrading the OpenTelemetry packages to the latest version, it seems that the `TracerProviderBuilder` class does not contain any `Configure` method. Hence, the following call in the `App4` does not compile.
> 
> ```cs
> .Configure((sp, builder) =>
> {
>     RedisCache cache = (RedisCache)sp.GetRequiredService<IDistributedCache>();
>     builder.AddRedisInstrumentation(cache.GetConnection());
> })
> ```

I'm aware that there has been a few breaking changes on the OpenTelemetry .NET SDK since I created this demo. I plan to upgrade the entire demo and the blog post in the next few days.

If you're using the latest version of the ``OpenTelemetry.Instrumentation.StackExchangeRedis`` package in ``App4``,  you can use the ``ConfigureRedisInstrumentation`` method. 
Here's an example:

```csharp
services.AddOpenTelemetry().WithTracing(builder =>
{
    var provider = services.BuildServiceProvider();
    IConfiguration config = provider
            .GetRequiredService<IConfiguration>();

    builder.AddAspNetCoreInstrumentation()
        .AddHttpClientInstrumentation()
        .AddRedisInstrumentation()
        .ConfigureRedisInstrumentation((sp, i) =>
        {
            var cache = (RedisCache)sp.GetRequiredService<IDistributedCache>();
            i.AddConnection(cache.GetConnection());
        })
        .AddSource(nameof(Worker))
        .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("App4"))
        .AddOtlpExporter(opts =>
        {
            opts.Endpoint =
                new Uri(
                    $"{config["Jaeger:Protocol"]}://{config["Jaeger:Host"]}:{config["Jaeger:Port"]}");
        }); ;
});
```
